const FLAG_MAP: Record<string, string> = {
  France: '🇫🇷',
  Senegal: '🇸🇳',
  Panama: '🇵🇦',
  Iraq: '🇮🇶',
  USA: '🇺🇸',
  'United States': '🇺🇸',
  Morocco: '🇲🇦',
  Algeria: '🇩🇿',
  'Cape Verde': '🇨🇻',
  'Cape Verde Islands': '🇨🇻',
  Spain: '🇪🇸',
  Austria: '🇦🇹',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Haiti: '🇭🇹',
  Belgium: '🇧🇪',
  Colombia: '🇨🇴',
  Egypt: '🇪🇬',
  Turkey: '🇹🇷',
  Brazil: '🇧🇷',
  Switzerland: '🇨🇭',
  'Saudi Arabia': '🇸🇦',
  'DR Congo': '🇨🇩',
  'Congo DR': '🇨🇩',
  Germany: '🇩🇪',
  Uruguay: '🇺🇾',
  Uzbekistan: '🇺🇿',
  'Czech Republic': '🇨🇿',
  'Czechia': '🇨🇿',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  Iran: '🇮🇷',
  Paraguay: '🇵🇾',
  Sweden: '🇸🇪',
  Mexico: '🇲🇽',
  Ecuador: '🇪🇨',
  "Côte d'Ivoire": '🇨🇮',
  'Ivory Coast': '🇨🇮',
  'Bosnia-Herzegovina': '🇧🇦',
  'Bosnia & Herzegovina': '🇧🇦',
  Netherlands: '🇳🇱',
  Australia: '🇦🇺',
  Qatar: '🇶🇦',
  Curacao: '🇨🇼',
  Curaçao: '🇨🇼',
  Argentina: '🇦🇷',
  Japan: '🇯🇵',
  'South Africa': '🇿🇦',
  Jordan: '🇯🇴',
  Canada: '🇨🇦',
  'South Korea': '🇰🇷',
  'Korea Republic': '🇰🇷',
  Norway: '🇳🇴',
  'New Zealand': '🇳🇿',
  Portugal: '🇵🇹',
  Croatia: '🇭🇷',
  Tunisia: '🇹🇳',
  Ghana: '🇬🇭',
};

export function getFlag(countryName: string): string {
  return FLAG_MAP[countryName] ?? '🏳️';
}
